spring.application.name=BudgetAnalizer
spring.datasource.url=jdbc:mysql://localhost:3306/expense_tracker
spring.datasource.username=root
spring.datasource.password=13692468

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true